import {
  Calculator,
  FunctionSquare,
  Triangle,
  Square,
  Hash,
  Star,
  Clock,
  BookOpen,
  LineChart,
  GraduationCap,
  Sigma,
  Box,
  Map,
  Wrench,
  Flame
} from "lucide-react";

export const CATEGORIES = [
  { id: "favorites", name: "Favorites", icon: Star },
  { id: "recent", name: "Recent", icon: Clock },
  { id: "popular", name: "Popular", icon: Flame },
  { id: "all", name: "All Tools", icon: Box },
  { id: "Basic Math", name: "Basic Math", icon: Calculator },
  { id: "Arithmetic & Number System", name: "Arithmetic & Number System", icon: Hash },
  { id: "Algebra", name: "Algebra", icon: FunctionSquare },
  { id: "Trigonometry", name: "Trigonometry", icon: Triangle },
  { id: "Geometry", name: "Geometry", icon: Square },
  { id: "Mensuration", name: "Mensuration", icon: Box },
  { id: "Coordinate Geometry", name: "Coordinate Geometry", icon: Map },
  { id: "Calculus", name: "Calculus", icon: Sigma },
  { id: "Advanced Math (JEE Level)", name: "Advanced Math (JEE Level)", icon: GraduationCap },
  { id: "Utilities", name: "Utilities", icon: Wrench },
  { id: "Formulas", name: "Formula Library", icon: BookOpen },
  { id: "Graphs", name: "Graph Viewer", icon: LineChart },
];
